name: "webapp-publisher"
description: "Publish your Webb Applications to the Azion Platform"

runs:
  using: "composite"
  steps:
    - run: go run ${{ github.action_path }}/webapppublisher.go
      shell: bash
