name: "webapp-publisher"
description: "Publish your Web Applications to the Azion Platform"

runs:
  using: "composite"
  steps:
    - run: |
        mydir=$(pwd)
        cd ${{ github.action_path }}
        go run ${{ github.action_path }}/webapppublisher.go
        if [ ${{ env.SHOULD_COMMIT }} = true ]
        then
          echo "Pushing Azion dir to remote"
          cd $mydir
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          rm -rf $mydir/azion/cells-site-template/.git
          rm $mydir/azion/webdev.env
          git add $mydir/azion/*
          git commit -m "chore: update azion directory"
          git push
        else
          echo "Not pushing Azion dir"
        fi
      shell: bash
