name: "webapp-publisher"
description: "Publish your Webb Applications to the Azion Platform"

runs:
  using: "composite"
  steps:
    - run: |
        go build -o ${{ github.action_path }}/webapppublisher ${{ github.action_path }}/webapppublisher.go
        ${{ github.action_path }}/webapppublisher
      shell: bash
