name: "webapp-publisher"
description: "Publish your Webb Applications to the Azion Platform"

runs:
  using: "composite"
  steps:
    - run: |
        node -v
        npm install react react-dom
        cd ${{ github.action_path }}
        go get github.com/go-git/go-git/v5
        go mod tidy
        go mod download
        go run ${{ github.action_path }}/webapppublisher.go
      shell: bash
