name: "webapp-publisher"
description: "Publish your Webb Applications to the Azion Platform"

runs:
  using: "composite"
  steps:
    - run: |
        go mod init webapp-publisher
        go get github.com/go-git/go-git/v5
        go mod tidy
        go mod download
        go run ${{ github.action_path }}/webapppublisher.go
      shell: bash
